## APARTMENT RENTAL IN GERMNAY: Consistency & Wrangling

### 6.1 Sourcing open data

### Importing Libraries & Dataframe

In [1]:
# Importing libraries
import pandas as pd
import numpy as np
import os

In [2]:
path=r'C:\Users\Jatin\Documents\ApartmentRentalInGermany\Data'

In [3]:
# Importing dataframe
df=pd.read_csv(os.path.join(path,'Original Data','immo_data.csv'))

In [4]:
pd.options.display.max_columns=None

### Conducting basic checks

In [5]:
# Checking dimensions
df.shape

(268850, 49)

In [6]:
# Checking basic data
df.head()

,regio1,serviceCharge,heatingType,telekomTvOffer,telekomHybridUploadSpeed,newlyConst,balcony,picturecount,pricetrend,telekomUploadSpeed,totalRent,yearConstructed,scoutId,noParkSpaces,firingTypes,hasKitchen,geo_bln,cellar,yearConstructedRange,baseRent,houseNumber,livingSpace,geo_krs,condition,interiorQual,petsAllowed,street,streetPlain,lift,baseRentRange,typeOfFlat,geo_plz,noRooms,thermalChar,floor,numberOfFloors,noRoomsRange,garden,livingSpaceRange,regio2,regio3,description,facilities,heatingCosts,energyEfficiencyClass,lastRefurbish,electricityBasePrice,electricityKwhPrice,date
0,Nordrhein_Westfalen,245.00,central_heating,ONE_YEAR_FREE,NaN,False,False,6,4.62,10.0,840.0,1965.0,96107057,1.0,oil,False,Nordrhein_Westfalen,True,2.0,595.0,244,86.00,Dortmund,well_kept,normal,NaN,Sch&uuml;ruferstra&szlig;e,Schüruferstraße,False,4,ground_floor,44269,4.0,181.4,1.0,3.0,4,True,4,Dortmund,Schüren,Die ebenerdig zu erreichende Erdgeschosswohnun...,Die Wohnung ist mit Laminat ausgelegt. Das Bad...,NaN,NaN,NaN,NaN,NaN,May19
1,Rheinland_Pfalz,134.00,self_contained_central_heating,ONE_YEAR_FREE,NaN,False,True,8,3.47,10.0,NaN,1871.0,111378734,2.0,gas,False,Rheinland_Pfalz,False,1.0,800.0,NaN,89.00,Rhein_Pfalz_Kreis,refurbished,normal,no,no_information,NaN,False,5,ground_floor,67459,3.0,NaN,NaN,NaN,3,False,4,Rhein_Pfalz_Kreis,Böhl_Iggelheim,Alles neu macht der Mai – so kann es auch für ...,NaN,NaN,NaN,2019.0,NaN,NaN,May19
2,Sachsen,255.00,floor_heating,ONE_YEAR_FREE,10.0,True,True,8,2.72,2.4,1300.0,2019.0,113147523,1.0,NaN,False,Sachsen,True,9.0,965.0,4,83.80,Dresden,first_time_use,sophisticated,NaN,Turnerweg,Turnerweg,True,6,apartment,1097,3.0,NaN,3.0,4.0,3,False,4,Dresden,Äußere_Neustadt_Antonstadt,Der Neubau entsteht im Herzen der Dresdner Neu...,"* 9 m² Balkon\n* Bad mit bodengleicher Dusche,...",NaN,NaN,NaN,NaN,NaN,Oct19
3,Sachsen,58.15,district_heating,ONE_YEAR_FREE,NaN,False,True,9,1.53,40.0,NaN,1964.0,108890903,NaN,district_heating,False,Sachsen,False,2.0,343.0,35,58.15,Mittelsachsen_Kreis,NaN,NaN,NaN,Gl&uuml;ck-Auf-Stra&szlig;e,Glück-Auf-Straße,False,2,other,9599,3.0,86.0,3.0,NaN,3,False,2,Mittelsachsen_Kreis,Freiberg,Abseits von Lärm und Abgasen in Ihre neue Wohn...,NaN,87.23,NaN,NaN,NaN,NaN,May19
4,Bremen,138.00,self_contained_central_heating,NaN,NaN,False,True,19,2.46,NaN,903.0,1950.0,114751222,NaN,gas,False,Bremen,False,1.0,765.0,10,84.97,Bremen,refurbished,NaN,NaN,Hermann-Henrich-Meier-Allee,Hermann-Henrich-Meier-Allee,False,5,apartment,28213,3.0,188.9,1.0,NaN,3,False,4,Bremen,Neu_Schwachhausen,Es handelt sich hier um ein saniertes Mehrfami...,Diese Wohnung wurde neu saniert und ist wie fo...,NaN,NaN,NaN,NaN,NaN,Feb20

### DATA WRANGLING

### a. Dropping columns

In [7]:
# Checking for missing values
df.isnull().sum()

regio1                           0
serviceCharge                 6909
heatingType                  44856
telekomTvOffer               32619
telekomHybridUploadSpeed    223830
newlyConst                       0
balcony                          0
picturecount                     0
pricetrend                    1832
telekomUploadSpeed           33358
totalRent                    40517
yearConstructed              57045
scoutId                          0
noParkSpaces                175798
firingTypes                  56964
hasKitchen                       0
geo_bln                          0
cellar                           0
yearConstructedRange         57045
baseRent                         0
houseNumber                  71018
livingSpace                      0
geo_krs                          0
condition                    68489
interiorQual                112665
petsAllowed                 114573
street                           0
streetPlain                  71013
lift                             0
baseRentRange                    0
typeOfFlat                   36614
geo_plz                          0
noRooms                          0
thermalChar                 106506
floor                        51309
numberOfFloors               97732
noRoomsRange                     0
garden                           0
livingSpaceRange                 0
regio2                           0
regio3                           0
description                  19747
facilities                   52924
heatingCosts                183332
energyEfficiencyClass       191063
lastRefurbish               188139
electricityBasePrice        222004
electricityKwhPrice         222004
date                             0
dtype: int64

In [8]:
# Dropping columns which are not necessary for analysis
df_drop=df.drop(columns=['telekomTvOffer','telekomHybridUploadSpeed','picturecount','pricetrend','telekomUploadSpeed','scoutId','noParkSpaces','firingTypes','geo_bln','yearConstructedRange','houseNumber','interiorQual','petsAllowed','street','streetPlain','baseRentRange','thermalChar','numberOfFloors','noRoomsRange','livingSpaceRange','geo_krs','description','facilities','heatingCosts','energyEfficiencyClass','lastRefurbish','electricityBasePrice','electricityKwhPrice','geo_plz'])

In [9]:
df_drop.shape

(268850, 20)

In [10]:
df_drop.head()

,regio1,serviceCharge,heatingType,newlyConst,balcony,totalRent,yearConstructed,hasKitchen,cellar,baseRent,livingSpace,condition,lift,typeOfFlat,noRooms,floor,garden,regio2,regio3,date
0,Nordrhein_Westfalen,245.00,central_heating,False,False,840.0,1965.0,False,True,595.0,86.00,well_kept,False,ground_floor,4.0,1.0,True,Dortmund,Schüren,May19
1,Rheinland_Pfalz,134.00,self_contained_central_heating,False,True,NaN,1871.0,False,False,800.0,89.00,refurbished,False,ground_floor,3.0,NaN,False,Rhein_Pfalz_Kreis,Böhl_Iggelheim,May19
2,Sachsen,255.00,floor_heating,True,True,1300.0,2019.0,False,True,965.0,83.80,first_time_use,True,apartment,3.0,3.0,False,Dresden,Äußere_Neustadt_Antonstadt,Oct19
3,Sachsen,58.15,district_heating,False,True,NaN,1964.0,False,False,343.0,58.15,NaN,False,other,3.0,3.0,False,Mittelsachsen_Kreis,Freiberg,May19
4,Bremen,138.00,self_contained_central_heating,False,True,903.0,1950.0,False,False,765.0,84.97,refurbished,False,apartment,3.0,1.0,False,Bremen,Neu_Schwachhausen,Feb20

### b. Renaming columns

In [11]:
# renaming some columns for better understanding
df_drop.rename(columns={'regio1':'state','regio2':'district','regio3':'city','noRooms':'numberOfRooms','newlyConst':'newlyConstructed'},inplace=True)

In [12]:
df_drop.head(60)

,state,serviceCharge,heatingType,newlyConstructed,balcony,totalRent,yearConstructed,hasKitchen,cellar,baseRent,livingSpace,condition,lift,typeOfFlat,numberOfRooms,floor,garden,district,city,date
0,Nordrhein_Westfalen,245.00,central_heating,False,False,840.00,1965.0,False,True,595.00,86.00,well_kept,False,ground_floor,4.0,1.0,True,Dortmund,Schüren,May19
1,Rheinland_Pfalz,134.00,self_contained_central_heating,False,True,NaN,1871.0,False,False,800.00,89.00,refurbished,False,ground_floor,3.0,NaN,False,Rhein_Pfalz_Kreis,Böhl_Iggelheim,May19
2,Sachsen,255.00,floor_heating,True,True,1300.00,2019.0,False,True,965.00,83.80,first_time_use,True,apartment,3.0,3.0,False,Dresden,Äußere_Neustadt_Antonstadt,Oct19
3,Sachsen,58.15,district_heating,False,True,NaN,1964.0,False,False,343.00,58.15,NaN,False,other,3.0,3.0,False,Mittelsachsen_Kreis,Freiberg,May19
4,Bremen,138.00,self_contained_central_heating,False,True,903.00,1950.0,False,False,765.00,84.97,refurbished,False,apartment,3.0,1.0,False,Bremen,Neu_Schwachhausen,Feb20
5,Schleswig_Holstein,142.00,gas_heating,False,True,NaN,1999.0,True,False,315.20,53.43,well_kept,False,apartment,2.0,NaN,False,Schleswig_Flensburg_Kreis,Struxdorf,Feb20
6,Sachsen,70.00,self_contained_central_heating,False,False,380.00,NaN,False,True,310.00,62.00,fully_renovated,False,NaN,2.0,1.0,True,Mittelsachsen_Kreis,Freiberg,Feb20
7,Bremen,88.00,central_heating,False,True,584.25,1959.0,False,True,452.25,60.30,NaN,False,ground_floor,3.0,NaN,False,Bremen,St._Magnus,Feb20
8,Baden_Württemberg,110.00,oil_heating,False,False,690.00,1970.0,True,True,580.00,53.00,well_kept,False,roof_storey,2.0,2.0,False,Emmendingen_Kreis,Denzlingen,Feb20
9,Nordrhein_Westfalen,95.00,self_contained_central_heating,False,False,NaN,1953.0,False,True,300.00,60.00,well_kept,False,apartment,2.5,2.0,False,Gelsenkirchen,Bulmke_Hüllen,Oct19
10,Sachsen,88.00,NaN,False,True,307.00,1930.0,False,True,219.00,40.20,NaN,False,apartment,2.0,3.0,False,Chemnitz,Sonnenberg,Oct19
11,Sachsen,155.00,central_heating,False,False,555.00,1892.0,False,True,400.00,80.00,well_kept,False,NaN,3.0,1.0,True,Mittelsachsen_Kreis,Frankenberg/Sachsen,May19
12,Rheinland_Pfalz,270.00,oil_heating,False,False,920.00,1912.0,False,False,650.00,100.00,mint_condition,False,ground_floor,4.0,NaN,True,Südliche_Weinstraße_Kreis,Frankweiler,May19
13,Nordrhein_Westfalen,200.00,central_heating,False,False,1150.00,1951.0,False,False,950.00,123.44,first_time_use_after_refurbishment,False,apartment,4.0,4.0,False,Hamm,Mitte,Oct19
14,Nordrhein_Westfalen,215.00,gas_heating,True,True,1320.65,2018.0,False,True,972.60,87.00,first_time_use,True,ground_floor,3.0,0.0,False,Dortmund,Kirchhörde,May19
15,Thüringen,80.00,district_heating,False,True,300.00,1990.0,False,True,220.00,36.63,first_time_use_after_refurbishment,False,apartment,1.0,4.0,False,Weimar,Schöndorf,Sep18
16,Hessen,220.00,oil_heating,False,True,970.00,NaN,False,True,750.00,87.00,well_kept,False,apartment,3.0,NaN,False,Main_Kinzig_Kreis,Hanau,Oct19
17,Sachsen,50.00,central_heating,False,False,325.00,1897.0,False,False,200.00,50.00,refurbished,False,roof_storey,2.0,3.0,True,Mittelsachsen_Kreis,Döbeln,Sep18
18,Nordrhein_Westfalen,121.00,central_heating,False,True,NaN,1914.0,False,True,329.00,65.00,well_kept,False,apartment,2.5,2.0,False,Duisburg,Obermarxloh,May19
19,Niedersachsen,290.00,district_heating,False,True,1878.48,2013.0,False,True,1343.48,127.95,mint_condition,True,apartment,5.0,1.0,False,Göttingen_Kreis,Göttingen,Oct19
20,Schleswig_Holstein,140.00,central_heating,False,True,1450.00,1978.0,False,True,1150.00,160.00,well_kept,False,ground_floor,4.0,0.0,True,Neumünster,Wittorf,Oct19
21,Baden_Württemberg,0.00,NaN,False,False,1190.00,NaN,False,False,1190.00,29.00,NaN,False,apartment,1.5,3.0,False,Stuttgart,Bad_Cannstatt,Oct19
22,Sachsen,346.00,central_heating,False,True,1946.00,NaN,False,False,1600.00,140.00,first_time_use_after_refurbishment,True,roof_storey,4.0,0.0,True,Leipzig,Lindenau,Oct19
23,Bayern,180.00,central_heating,False,False,2030.00,1871.0,True,True,1850.00,81.00,well_kept,False,apartment,2.0,4.0,False,München,Altstadt,Oct19
24,Hamburg,140.00,central_heating,False,True,760.00,1953.0,False,True,620.00,55.89,fully_renovated,False,apartment,3.0,2.0,False,Hamburg,Horn,May19
25,Niedersachsen,80.00,district_heating,False,False,396.00,1890.0,False,False,316.00,31.00,NaN,False,roof_storey,1.5,NaN,False,Braunschweig,Westliches_Ringgebiet,Feb20
26,Baden_Württemberg,20.00,NaN,False,False,355.00,1902.0,False,False,335.00,12.00,NaN,False,other,1.0,NaN,False,Esslingen_Kreis,Nürtingen,Feb20
27,Sachsen_Anhalt,147.32,district_heating,False,True,447.62,1977.0,False,True,300.30,56.66,NaN,True,apartment,3.0,6.0,False,Magdeburg,Kannenstieg,Feb20
28,Bayern,0.00,NaN,False,True,2400.00,1956.0,False,False,2400.00,61.00,NaN,True,NaN,3.0,1.0,False,München,Schwabing_West,May19
29,Mecklenburg_Vorpommern,104.02,district_heating,True,True,624.10,2018.0,False,True,520.08,47.28,first_time_use,True,raised_ground_floor,2.0,NaN,False,Schwerin,Paulsstadt,May19
30,Bayern,170.00,floor_heating,False,True,970.00,1974.0,True,True,800.00,106.08,NaN,False,ground_floor,2.0,NaN,False,Passau,Haidenhof_Süd,Sep18
31,Nordrhein_Westfalen,130.00,district_heating,False,True,445.18,1976.0,False,True,315.18,60.00,NaN,True,terraced_flat,2.0,0.0,True,Mettmann_Kreis,Erkrath,Sep18
32,Bayern,0.00,NaN,False,True,2780.00,2016.0,False,False,2780.00,100.00,NaN,True,NaN,3.0,5.0,False,München,Milbertshofen,Feb20
33,Sachsen,80.00,central_heating,False,False,245.00,1914.0,True,False,165.00,35.00,fully_renovated,False,ground_floor,2.0,NaN,False,Vogtlandkreis,Reichenbach_im_Vogtland,Oct19
34,Hessen,260.00,wood_pellet_heating,False,False,1195.00,2013.0,True,False,935.00,35.00,mint_condition,False,NaN,1.0,3.0,False,Groß_Gerau_Kreis,Raunheim,Oct19
35,Sachsen,140.00,central_heating,False,False,548.00,1996.0,False,True,408.00,58.22,NaN,False,apartment,2.0,1.0,False,Sächsische_Schweiz_Osterzgebirge_Kreis,Freital,May19
36,Sachsen,140.00,district_heating,False,True,546.00,1966.0,False,True,406.00,74.00,refurbished,False,apartment,3.0,3.0,False,Görlitz_Kreis,Löbau,May19
37,Nordrhein_Westfalen,100.00,central_heating,False,False,350.00,NaN,False,False,250.00,36.00,NaN,False,half_basement,1.5,NaN,False,Rheinisch_Bergischer_Kreis,Bergisch_Gladbach,Oct19
38,Nordrhein_Westfalen,150.00,NaN,False,False,570.00,NaN,False,False,400.00,70.00,NaN,False,NaN,3.5,1.0,False,Essen,Altenessen_Nord,Oct19
39,Sachsen,103.70,central_heating,False,True,NaN,1928.0,False,True,246.00,43.93,well_kept,False,ground_floor,2.0,NaN,True,Meißen_Kreis,Riesa,Feb20
40,Baden_Württemberg,230.00,central_heating,False,True,1115.00,NaN,False,True,850.00,100.00,well_kept,False,maisonette,3.0,3.0,False,Mannheim,Käfertal,May19
41,Niedersachsen,196.80,NaN,False,True,NaN,1974.0,False,True,333.20,70.04,NaN,False,apartment,3.0,1.0,False,Wesermarsch_Kreis,Brake_Unterweser,Sep18
42,Nordrhein_Westfalen,200.00,district_heating,False,True,753.98,1994.0,True,True,553.98,87.33,well_kept,True,apartment,3.0,NaN,True,Hochsauerlandkreis,Arnsberg,Oct19
43,Nordrhein_Westfalen,160.00,central_heating,False,False,NaN,1975.0,True,False,400.00,65.00,well_kept,False,roof_storey,2.0,1.0,False,Unna_Kreis,Unna,Feb20
44,Sachsen,130.00,oil_heating,False,True,396.00,1987.0,False,True,266.00,58.95,well_kept,False,apartment,3.0,1.0,True,Bautzen_Kreis,Radibor,Oct19
45,Berlin,320.00,central_heating,False,True,1140.00,NaN,True,False,820.00,77.00,NaN,True,ground_floor,3.0,0.0,False,Berlin,Staaken_Spandau,Feb20
46,Hessen,0.00,NaN,False,False,2190.00,1900.0,False,False,2190.00,96.00,NaN,False,NaN,4.0,NaN,False,Frankfurt_am_Main,Nordend_West,May19
47,Sachsen_Anhalt,80.00,central_heating,False,False,340.00,1920.0,False,False,260.00,40.00,modernized,False,roof_storey,2.0,3.0,False,Halle_Saale,Radewell_Osendorf,May19
48,Schleswig_Holstein,121.50,NaN,True,True,1113.00,2019.0,True,False,870.00,81.00,NaN,False,NaN,3.0,2.0,False,Steinburg_Kreis,Herzhorn,Oct19
49,Bayern,185.00,NaN,False,False,NaN,2007.0,False,False,850.00,77.08,NaN,False,NaN,3.0,NaN,False,Aschaffenburg,Obernauer_Kolonie,May19
50,Brandenburg,50.00,central_heating,False,True,377.00,1980.0,False,True,285.00,36.29,fully_renovated,True,apartment,1.0,1.0,False,Oder_Spree_Kreis,Fürstenwalde/Spree,Feb20
51,Bremen,120.00,central_heating,False,False,380.00,1912.0,False,False,260.00,62.13,NaN,False,apartment,3.0,5.0,False,Bremerhaven,Lehe,Sep18
52,Sachsen,170.00,gas_heating,False,False,535.00,1905.0,False,True,365.00,79.00,well_kept,False,other,3.0,1.0,False,Zwickau_Kreis,Hohenstein_Ernstthal,Feb20
53,Hessen,130.00,central_heating,False,False,820.00,1909.0,False,False,690.00,52.00,well_kept,False,ground_floor,2.0,0.0,False,Frankfurt_am_Main,Heddernheim,Feb20
54,Sachsen,156.00,central_heating,False,True,501.00,NaN,False,True,340.00,65.00,fully_renovated,True,apartment,3.0,1.0,False,Chemnitz,Lutherviertel,Oct19
55,Sachsen,100.00,self_contained_central_heating,False,False,330.00,NaN,False,False,230.00,42.00,refurbished,False,roof_storey,2.0,3.0,False,Nordsachsen_Kreis,Bad_Düben,Oct19
56,Sachsen,110.00,central_heating,False,False,NaN,1995.0,True,True,410.00,50.18,fully_renovated,True,apartment,2.0,2.0,True,Dresden,Striesen_Ost,Oct19
57,Mecklenburg_Vorpommern,113.80,district_heating,False,False,453.80,1969.0,False,True,340.00,42.52,first_time_use_after_refurbishment,False,apartment,2.0,3.0,False,Schwerin,Lankow,Sep18
58,Sachsen,40.00,central_heating,False,False,340.00,1930.0,False,False,240.00,44.66,refurbished,False,roof_storey,2.0,3.0,False,Nordsachsen_Kreis,Schkeuditz,Sep18
59,Sachsen,85.00,central_heating,False,True,425.00,1909.0,True,False,280.00,53.12,well_kept,False,apartment,2.0,2.0,False,Chemnitz,Bernsdorf,Feb20

### c. Changing data types

In [13]:
# Changing data type from float to int
df_drop['numberOfRooms']=df_drop['numberOfRooms'].astype('int64')

In [14]:
df_drop['numberOfRooms'].dtype

dtype('int64')

## DATA CONSISTENCY CHECKS

### a. Checking for mixed type data

In [15]:
# Checking for mixed type data
for col in df_drop.columns.tolist():
  weird = (df_drop[[col]].applymap(type) != df_drop[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_drop[weird]) > 0:
    print (col)

heatingType
condition
typeOfFlat

In [16]:
# Updating heatingType column data type to string
df_drop['heatingType']=df_drop['heatingType'].astype('str')

In [17]:
# Updating condition column data type to string
df_drop['condition']=df_drop['condition'].astype('str')

In [18]:
# Updating typeOfFlat column data type to string
df_drop['typeOfFlat']=df_drop['typeOfFlat'].astype('str')

In [19]:
# Checking again for mixed type data
for col in df_drop.columns.tolist():
  weird = (df_drop[[col]].applymap(type) != df_drop[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_drop[weird]) > 0:
    print (col)

NO mixed type data found.

## b. Checking for missing values

In [20]:
# Checking for missing values
df_drop.isnull().sum()

state                   0
serviceCharge        6909
heatingType             0
newlyConstructed        0
balcony                 0
totalRent           40517
yearConstructed     57045
hasKitchen              0
cellar                  0
baseRent                0
livingSpace             0
condition               0
lift                    0
typeOfFlat              0
numberOfRooms           0
floor               51309
garden                  0
district                0
city                    0
date                    0
dtype: int64

In [21]:
# Checking descriptive Statistics
df_drop.describe()

,serviceCharge,totalRent,yearConstructed,baseRent,livingSpace,numberOfRooms,floor
count,261941.000000,2.283330e+05,211805.000000,2.688500e+05,268850.000000,268850.000000,217541.000000
mean,151.206113,9.013315e+02,1966.400590,6.941294e+02,74.355548,2.595808,2.122405
std,308.295790,3.323833e+04,46.992207,1.953602e+04,254.759208,2.630466,3.634934
min,0.000000,0.000000e+00,1000.000000,0.000000e+00,0.000000,1.000000,-1.000000
25%,95.000000,4.698000e+02,1950.000000,3.380000e+02,54.000000,2.000000,1.000000
50%,135.000000,6.500000e+02,1973.000000,4.900000e+02,67.320000,3.000000,2.000000
75%,190.000000,9.850000e+02,1996.000000,7.990000e+02,87.000000,3.000000,3.000000
max,146118.000000,1.575154e+07,2090.000000,9.999999e+06,111111.000000,999.000000,999.000000

In [22]:
# To calculate median 
df_drop.median()

C:\Users\Jatin\AppData\Local\Temp\ipykernel_19760\3299781122.py:2: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_drop.median()

serviceCharge        135.00
newlyConstructed       0.00
balcony                1.00
totalRent            650.00
yearConstructed     1973.00
hasKitchen             0.00
cellar                 1.00
baseRent             490.00
livingSpace           67.32
lift                   0.00
numberOfRooms          3.00
floor                  2.00
garden                 0.00
dtype: float64

In [23]:
## replacing missing values with its mean value
df_drop['serviceCharge'].fillna(151,inplace=True)

In [24]:
# # replacing missing values with its mean value
df_drop['totalRent'].fillna(902,inplace=True)

In [25]:
# replacing missing values with its median value
df_drop['yearConstructed'].fillna(1973,inplace=True)

In [26]:
# replacing missing values with its median value
df_drop['floor'].fillna(2,inplace=True)

In [27]:
# Checking for missing values
df_drop.isnull().sum()

state               0
serviceCharge       0
heatingType         0
newlyConstructed    0
balcony             0
totalRent           0
yearConstructed     0
hasKitchen          0
cellar              0
baseRent            0
livingSpace         0
condition           0
lift                0
typeOfFlat          0
numberOfRooms       0
floor               0
garden              0
district            0
city                0
date                0
dtype: int64

 All missing values are replaced by mean or median of selected columns.

In [28]:
df_drop.head(10)

,state,serviceCharge,heatingType,newlyConstructed,balcony,totalRent,yearConstructed,hasKitchen,cellar,baseRent,livingSpace,condition,lift,typeOfFlat,numberOfRooms,floor,garden,district,city,date
0,Nordrhein_Westfalen,245.00,central_heating,False,False,840.00,1965.0,False,True,595.00,86.00,well_kept,False,ground_floor,4,1.0,True,Dortmund,Schüren,May19
1,Rheinland_Pfalz,134.00,self_contained_central_heating,False,True,902.00,1871.0,False,False,800.00,89.00,refurbished,False,ground_floor,3,2.0,False,Rhein_Pfalz_Kreis,Böhl_Iggelheim,May19
2,Sachsen,255.00,floor_heating,True,True,1300.00,2019.0,False,True,965.00,83.80,first_time_use,True,apartment,3,3.0,False,Dresden,Äußere_Neustadt_Antonstadt,Oct19
3,Sachsen,58.15,district_heating,False,True,902.00,1964.0,False,False,343.00,58.15,nan,False,other,3,3.0,False,Mittelsachsen_Kreis,Freiberg,May19
4,Bremen,138.00,self_contained_central_heating,False,True,903.00,1950.0,False,False,765.00,84.97,refurbished,False,apartment,3,1.0,False,Bremen,Neu_Schwachhausen,Feb20
5,Schleswig_Holstein,142.00,gas_heating,False,True,902.00,1999.0,True,False,315.20,53.43,well_kept,False,apartment,2,2.0,False,Schleswig_Flensburg_Kreis,Struxdorf,Feb20
6,Sachsen,70.00,self_contained_central_heating,False,False,380.00,1973.0,False,True,310.00,62.00,fully_renovated,False,nan,2,1.0,True,Mittelsachsen_Kreis,Freiberg,Feb20
7,Bremen,88.00,central_heating,False,True,584.25,1959.0,False,True,452.25,60.30,nan,False,ground_floor,3,2.0,False,Bremen,St._Magnus,Feb20
8,Baden_Württemberg,110.00,oil_heating,False,False,690.00,1970.0,True,True,580.00,53.00,well_kept,False,roof_storey,2,2.0,False,Emmendingen_Kreis,Denzlingen,Feb20
9,Nordrhein_Westfalen,95.00,self_contained_central_heating,False,False,902.00,1953.0,False,True,300.00,60.00,well_kept,False,apartment,2,2.0,False,Gelsenkirchen,Bulmke_Hüllen,Oct19

In [29]:
df_drop.shape

(268850, 20)

### c. Checking for duplicate values

In [30]:
# Creating a subset that contain only rows with duplicate values
df_dups = df_drop[df_drop.duplicated()]

In [31]:
df_dups

,state,serviceCharge,heatingType,newlyConstructed,balcony,totalRent,yearConstructed,hasKitchen,cellar,baseRent,livingSpace,condition,lift,typeOfFlat,numberOfRooms,floor,garden,district,city,date
2811,Sachsen,220.00,central_heating,False,False,678.00,1920.0,True,False,458.00,62.35,refurbished,False,nan,2,2.0,False,Leipzig,Mockau_Süd,May19
3114,Sachsen,121.00,central_heating,False,False,371.00,1973.0,True,True,250.00,54.91,fully_renovated,False,nan,2,1.0,True,Chemnitz,Hilbersdorf,Oct19
7555,Sachsen,76.00,central_heating,False,False,485.00,1989.0,False,True,332.00,63.70,mint_condition,False,apartment,3,4.0,False,Bautzen_Kreis,Kamenz,May19
9410,Sachsen,260.00,district_heating,True,True,1295.00,2019.0,False,False,1035.00,129.26,first_time_use,True,maisonette,4,1.0,True,Leipzig,Böhlitz_Ehrenberg,Feb20
11601,Nordrhein_Westfalen,35.00,nan,False,False,902.00,1973.0,False,False,620.00,44.00,nan,False,apartment,2,1.0,False,Kleve_Kreis,Kleve,Oct19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268464,Baden_Württemberg,350.00,heat_pump,True,True,1800.00,2018.0,True,True,1450.00,135.00,first_time_use,False,apartment,5,1.0,False,Tübingen_Kreis,Kusterdingen,May19
268560,Schleswig_Holstein,80.40,district_heating,False,False,389.23,1998.0,False,True,246.83,40.99,nan,False,ground_floor,1,0.0,False,Neumünster,Innenstadt,May19
268577,Baden_Württemberg,300.00,district_heating,False,False,2660.00,1871.0,True,True,2200.00,87.00,fully_renovated,True,apartment,2,1.0,False,Heidelberg,Bergheim,Feb20
268786,Sachsen,255.43,nan,True,True,1123.88,2019.0,False,False,868.45,102.17,mint_condition,False,apartment,4,2.0,False,Leipzig,Zentrum_Südost,May19
268801,Mecklenburg_Vorpommern,68.00,gas_heating,False,True,258.00,1999.0,False,True,190.00,28.54,negotiable,False,apartment,1,1.0,False,Mecklenburg_Strelitz_Kreis,Friedland,Feb20

2939 duplicate values are found.

In [32]:
# To remove duplicates
df_clean=df_drop.drop_duplicates()

In [33]:
df_clean.shape

(265911, 20)

There were 2939 duplicate values found. It has been dropped and now remaining with 265911 rows.

In [34]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 265911 entries, 0 to 268849
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   state             265911 non-null  object
 1   serviceCharge     265911 non-null  float64
 2   heatingType       265911 non-null  object
 3   newlyConstructed  265911 non-null  bool
 4   balcony           265911 non-null  bool
 5   totalRent         265911 non-null  float64
 6   yearConstructed   265911 non-null  float64
 7   hasKitchen        265911 non-null  bool
 8   cellar            265911 non-null  bool
 9   baseRent          265911 non-null  float64
 10  livingSpace       265911 non-null  float64
 11  condition         265911 non-null  object
 12  lift              265911 non-null  bool
 13  typeOfFlat        265911 non-null  object
 14  numberOfRooms     265911 non-null  int64
 15  floor             265911 non-null  float64
 16  garden            265911 non-null  bool
 17  district          265911 non-null  object
 18  city              265911 non-null  object
 19  date              265911 non-null  object
dtypes: bool(6), float64(6), int64(1), object(7)
memory usage: 32.0+ MB

In [35]:
# Changing data type from float to int
df_clean['yearConstructed']=df_clean['yearConstructed'].astype('int64')

C:\Users\Jatin\AppData\Local\Temp\ipykernel_19760\4292057266.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['yearConstructed']=df_clean['yearConstructed'].astype('int64')

In [36]:
df_clean['yearConstructed'].dtype

dtype('int64')

In [37]:
# # Changing data type from float to int
df_clean['floor']=df_clean['floor'].astype('int64')

C:\Users\Jatin\AppData\Local\Temp\ipykernel_19760\3571353479.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['floor']=df_clean['floor'].astype('int64')

In [38]:
df_clean['floor'].dtype

dtype('int64')

In [39]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 265911 entries, 0 to 268849
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   state             265911 non-null  object
 1   serviceCharge     265911 non-null  float64
 2   heatingType       265911 non-null  object
 3   newlyConstructed  265911 non-null  bool
 4   balcony           265911 non-null  bool
 5   totalRent         265911 non-null  float64
 6   yearConstructed   265911 non-null  int64
 7   hasKitchen        265911 non-null  bool
 8   cellar            265911 non-null  bool
 9   baseRent          265911 non-null  float64
 10  livingSpace       265911 non-null  float64
 11  condition         265911 non-null  object
 12  lift              265911 non-null  bool
 13  typeOfFlat        265911 non-null  object
 14  numberOfRooms     265911 non-null  int64
 15  floor             265911 non-null  int64
 16  garden            265911 non-null  bool
 17  district          265911 non-null  object
 18  city              265911 non-null  object
 19  date              265911 non-null  object
dtypes: bool(6), float64(4), int64(3), object(7)
memory usage: 32.0+ MB

In [40]:
df_clean.head()

,state,serviceCharge,heatingType,newlyConstructed,balcony,totalRent,yearConstructed,hasKitchen,cellar,baseRent,livingSpace,condition,lift,typeOfFlat,numberOfRooms,floor,garden,district,city,date
0,Nordrhein_Westfalen,245.00,central_heating,False,False,840.0,1965,False,True,595.0,86.00,well_kept,False,ground_floor,4,1,True,Dortmund,Schüren,May19
1,Rheinland_Pfalz,134.00,self_contained_central_heating,False,True,902.0,1871,False,False,800.0,89.00,refurbished,False,ground_floor,3,2,False,Rhein_Pfalz_Kreis,Böhl_Iggelheim,May19
2,Sachsen,255.00,floor_heating,True,True,1300.0,2019,False,True,965.0,83.80,first_time_use,True,apartment,3,3,False,Dresden,Äußere_Neustadt_Antonstadt,Oct19
3,Sachsen,58.15,district_heating,False,True,902.0,1964,False,False,343.0,58.15,nan,False,other,3,3,False,Mittelsachsen_Kreis,Freiberg,May19
4,Bremen,138.00,self_contained_central_heating,False,True,903.0,1950,False,False,765.0,84.97,refurbished,False,apartment,3,1,False,Bremen,Neu_Schwachhausen,Feb20

### EXPORTING DATAFRAME

In [41]:
df.to_csv(os.path.join(path,'Prepared Data','df_clean.csv'))